# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Default applications
$terminal = kitty
$fileManager = nautilus --new-window
$browser = zen-browser --new-window
$passwordManager = 1password
$messenger = signal-desktop
$webapp = zen-browser --new-window
$mail = brave-browser --app=https://mail.proton.me/u/0/inbox
$claude = claude-desktop

# My configs
source = $HOME/.config/hypr/monitors.conf
source = $HOME/.config/hypr/autostart.conf
source = $HOME/.config/hypr/bindings.conf
source = $HOME/.config/hypr/envs.conf
source = $HOME/.config/hypr/looknfeel.conf
source = $HOME/.config/hypr/input.conf
source = $HOME/.config/hypr/windows.conf
source = $HOME/.config/hypr/theme.conf

