# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Window rule syntax updated for Hyprland 0.53+
windowrule = suppress_event maximize, match:class .*

# Force chromium into a tile to deal with --app bug
windowrule = tile on, match:class ^(Chromium)$

# Float sound and bluetooth settings
windowrule = float on, match:class ^(org.pulseaudio.pavucontrol|blueberry.py)$

# Float Steam, fullscreen RetroArch
windowrule = float on, match:class ^(steam)$
windowrule = fullscreen on, match:class ^(com.libretro.RetroArch)$

# Prevent Signal from opening fullscreen
windowrule = tile on, match:class ^(signal)$

windowrule = opacity 1 1, match:class .*
windowrule = opacity 1 1, match:title ^(youtube.com_/)$
windowrule = opacity 1 1, match:class ^(zoom|vlc|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta)$
windowrule = opacity 1 1, match:class ^(com.libretro.RetroArch|steam)$

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# Proper background blur for wofi
layerrule = blur on, ignore_alpha 1, match:namespace wofi

# Float in the middle for clipse clipboard manager
windowrule = float on, match:class clipse
windowrule = size 622 652, match:class clipse
windowrule = stay_focused on, match:class clipse

# Autostart Ghostty in fullscreen on workspace 10
windowrule = fullscreen on, match:class ^(com.mitchellh.ghostty)$, match:workspace 10
